apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: ghcr.io/bewestphal/demo-app:e9aa3fc260ade7bcac537a4e61bed703862e0500
        name: demo-app
        ports:
        - containerPort: 8080
